version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    # Using docs/requirements.txt which *should* use recent dependencies to build docs
    # FOR FUTURE CONSIDERATION: REMOVE in favor of adding extra_requirements: [docs]
    # back into to install method configuration below, once doc tools are updated in:
    # pyproject.toml
    - requirements: docs/requirements.txt
    - method: pip
      path: .
