name: Lint
on: [push, pull_request]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Install dependencies
        run: poetry install --no-dev
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install pyright
        run: npm install -g pyright
      - name: Pyright check
        run: poetry run pyright InquirerLib

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0
